# sso-config.yaml
users:
  - admin@bagitek.com
  - adenijimujeeb3969@gmail.com  # Uncomment when needed

groups:
  data-platform-dev-group:    # Dev environment group
    - admin@bagitek.com
    # - adenijimujeeb3969@gmail.com

  data-platform-prod-group:   # Prod environment group
    - admin@bagitek.com
    # - adenijimujeeb3969@gmail.com
