name: Terraform Deployment

on:
  push:
    branches: 
      - main      # Trigger for the prod environment
      - dev       # Trigger for the dev environment
    paths:
      - 'aws-identity-setup-tf/**'   # Monitor Terraform directory
      - '.github/workflows/ci_cd_deployment.yaml'  # Monitor changes to workflow

env:
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "TF_VAR_environment=prod" >> $GITHUB_ENV
          else
            echo "TF_VAR_environment=dev" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials with secrets
        id: configure_aws_secrets
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install CI Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          make install_python_deps

      - name: AWS STS GetCallerIdentity and Init, Plan Terraform
        run: |
          aws sts get-caller-identity
          terraform init
          echo "========"
          terraform plan
          echo "========"

      - name: AWS STS GetCallerIdentity and Init, Apply Terraform
        run: |
          make apply
