name: pr_add_user_us

on:
  pull_request:
    branches: [ main ]
    path:
    - 'users-identity/users-identity-us/people-prod.json'
    - 'users-identity/users-identity-us/people-stg.json'
    - 'users-identity/users-identity-us/people-dev.json'
    - 'tf-identity-setup/**'
    - '.github/workflows/pr_add_user_us.yaml'

env:
    AWS_REGION: us-east-1

permissions:
    id-token: write
    contents: read
    
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      authentication_success: ${{ steps.auth_status.outputs.authenticated }}
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2

      - name: Configure AWS OPENIDC Authentication
        id: configure_aws_credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::637423205666:role/GitHubAction-AssumeRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure AWS credentials with secrets
        if: failure()  # This step only runs if the previous authentication step fails
        id: configure_aws_secrets
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Set authentication success status
        id: auth_status
        run: |
          if [ "${{ steps.configure_aws_credentials.outcome }}" == "success" ] || [ "${{ steps.configure_aws_secrets.outcome }}" == "success" ]; then
            echo "::set-output name=authenticated::true"
          else
            echo "::set-output name=authenticated::false"
          fi

      - name: Install CI Dependencies
        if: steps.auth_status.outputs.authenticated == 'true'
        run: sudo apt-get update && sudo apt-get install build-essential && make install_python_deps

      - name: Read JSON files and export as environment variables
        if: steps.auth_status.outputs.authenticated == 'true'
        run: |
          export PEOPLE_PROD=$(cat users-identity/users-identity-us/people-prod.json)
          export PEOPLE_STG=$(cat users-identity/users-identity-us/people-stg.json)
          export PEOPLE_DEV=$(cat users-identity/users-identity-us/people-dev.json)

      - name: AWS STS GetCallerIdentity and Init, Apply Terraform
        if: steps.auth_status.outputs.authenticated == 'true'
        run: |
          aws sts get-caller-identity
          make init
          echo "Running linter, if the job fails here, all you have to do is run make tf_lint_with_write commit and push"
          echo "========"
          make tf_lint_without_write
          echo "========"
          make plan
          echo "========"